server:
  port: 8088

spring:
  application:
    name: show-query-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/show-read-service

  security:
    oauth2:

      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

      client:
        registration:
          internal-client:
            provider: auth-provider
            client-id: auth-service
            client-secret: auth-secret
            authorization-grant-type: client_credentials
            scope: internal.write
        provider:
          auth-provider:
            token-uri: http://localhost:8081/oauth2/token


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: show-query-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

